services:
  springventory:
    image: springventory
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_NAME: &dbName inventory
      DB_USERNAME: &dbUsername admin
      DB_PASSWORD: &dbPassword pleaseChangeMe
    depends_on:
      - postgres

  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_DB: *dbName
      POSTGRES_USER: *dbUsername
      POSTGRES_PASSWORD: *dbPassword